import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Playfair_Display } from 'next/font/google';
import { Diplomata_SC } from 'next/font/google';
import Footer from "@/components/layout/Footer";
import { LenisProvider } from "@/lib/lenis";

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
});

const diplomata = Diplomata_SC({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-diplomata',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${diplomata.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <LenisProvider>
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
